export const INJECTABLE_METADATA = 'INJECTABLE_METADATA';
export const INJECTABLE_PROPERTY_METADATA = 'INJECTABLE_PROPERTY_METADATA';

export enum MetadataKey {
  DOMAIN = 'DOMAIN_METADATA',
  METHOD = 'METHOD_METADATA',
  PATH = 'PATH_METADATA',
  MIDDLEWARE = 'MIDDLEWARE_METADATA',
  VALIDATOR = 'VALIDATOR_METADATA',
  BODY = 'BODY_METADATA',
  QUERY = 'QUERY_METADATA',
  PARAM = 'PARAM_METADATA',
  CONTEXT = 'CONTEXT_METADATA'
}